### ISSUE TITLE
Support botbuilder 4.8 or over

### ISSUE THREAD

**Issue by da351hon** [wictorwilen/express-msteams-host#4]
I use  Microsoft Teams Yeoman generator to develop bot services.
Now I would like to upgrade botbuilder SDK version to 4.8, because some APIs will be deprecated as follows:
https://docs.microsoft.com/microsoftteams/platform/resources/team-chat-member-api-changes
I hope express-msteams-host support botbuilder 4.8 or over, now It supports 4.7.1.

**Comment by wictorwilen** [comment]
Yes, it will work - I do that all the time. There are some incompabilities and issues known specifically when using messaging extensions, due to bugs in 4.8+. see https://github.com/microsoft/botbuilder-js/issues/2332

**Comment by felipeplets** [comment]
Hello @wictorwilen and thanks for the library!

Although we can update to newer versions this actually causes incompatibility issues because of the way the dependencies are specified in the library `package.json`. 

I've issued the PR fixing the issue. 

But let me give more context on the issue I am facing and why this update would fix it: 

- Although I've been using Teams and Bots for a while, I decided to test a new project of mine using https://github.com/pnp/generator-teams
- I've installed it, but for the project I'm starting I need the latest version so next step was updating botbuilder libraries to 4.10.x
- After updating I started facing a very weird issue, my IDE does show any error, the TS compiler either, but once the code runs and I call `TeamsInfo.getMember` API it raises an exception saying that `getConversationMember` is not a method on `connectorClient.conversations` (the error is raise in line 180 in `node_modules/botbuilder/src/teamsInfo.ts` for reference)
- So I opened the class that contains the definition for the `conversations` (`node_modules/botframework-connector/src/connectorApi/operations/conversations.ts`) and the method is there, so I went to the transpiled code (`node_modules/botframework-connector/lib/connectorApi/operations/conversations.js`) and again the method is there. 
- So I decided to debug in runtime and voila, the script that is been loaded is not from the class above (that is used by the IDE and transpiler), but it is actually loading the class `node_modules/express-msteams-host/node_modules/botframework-connector/lib/connectorApi/operations/conversations.js` that as you can see is inside express-msteams-host dependencies. 
- This happens because `express-msteams-host` is defining a specific version as it dependency, so when the conflict happen NPM resolves this by adding the specific version by adding the specific dependency inside the dependency that requires it, not respecting it as a peerDependency. 
- To fix there are two possible solutions. The first is the one in my PR, making it enable to use any minor or patch version higher than 4.7.1. The second possible solution would be a breaking change but in my opinion is the ideal and is using peerDependencies instead of a direct dependency. 

For a deeper understanding on the dependency tree there are some visual tools and I took a screenshot that shows the issue and the current dependency tree: 

![Screen Shot 2020-09-17 at 9 00 57 PM](https://user-images.githubusercontent.com/119980/93545382-420a3b00-f92e-11ea-82b6-c35537d3d074.png)

**Comment by wictorwilen** [comment]
Thanks a bunch for this, and this detailed answer. I've suffered myself from this as well :-). It was a deliberate decision to specify version in one of the early 4.x versions, since they did some breaking changes where I could not use a flexible min version. I'll take a look at the PR and try to include it ASAP

**Comment by felipeplets** [comment]
Good to know. For that use case, when there is a reason for fixing the version, I recommend using peerDependencies because then although npm will warn the user, updating to newer version will still be possible without breaking (if the breaking change is not an issue anymore or if the user is not using the library feature that would break). 

Some more details on peerDependencies: https://nodejs.org/es/blog/npm/peer-dependencies/

Also, I suggest documenting this kind of hard dependency on the readme once we face them in lib. 

Thank you for the great work and let me know if you have further questions.

**Comment by wictorwilen** [comment]
Now merged into `preview`
